# Importing the necessary library

In [1]:
import numpy as np

# Creating list

In [2]:
my_list=[1,2,3]

In [3]:
my_list

[1, 2, 3]

# Checking the list type

In [4]:
type(my_list)

list

# Converting the list into array :

In [5]:
my_arr=np.array(my_list)

In [6]:
my_arr

array([1, 2, 3])

# Checking my_arr type :

In [7]:
type(my_arr)

numpy.ndarray

# Nested list :

In [8]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]

In [9]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# Converting (my_matrix) list into array:

In [10]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# To create an array:

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# To create an array with step size:

In [12]:
np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

# To create an array of zeros:

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

# To create 2D array of zeros:

In [15]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# To create 2D array of ones:

In [16]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# To create a limited array with number of included objects

In [17]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [18]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [19]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

# To get the length of the following array:

In [21]:
len(np.linspace(0,5,21))

21

# To create a matrix:

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# To create an array randomly contains numbers it's value between 0 & 1:

In [23]:
np.random.rand(5,2)

array([[0.76993139, 0.8576731 ],
       [0.30878131, 0.45359648],
       [0.06095935, 0.00271411],
       [0.50245864, 0.11281946],
       [0.62363722, 0.00272216]])

# To create an array randomly contain 0 & 1 as well as 2 and -ve value:

In [25]:
np.random.randn(4,3)

array([[-2.31223573, -0.21750191, -1.41332064],
       [-0.20117931, -0.70290021, -1.4707576 ],
       [ 1.77070917, -0.37303617, -1.59675818],
       [-2.23966298,  0.45030453,  2.02249306]])

# To create an array with rendom integer value:

In [26]:
np.random.randint(0,101,5)

array([34, 23, 54, 74, 32])

# To create a rendom integer array with 2D:

In [33]:
np.random.randint(0,101,(4,5))

array([[ 46, 100,  80,  51,  82],
       [ 86,   9,  54,  83,  17],
       [ 88,  21,  49,  93,  62],
       [ 33,  91,  58,  34,  12]])

# To create an array randomly once only, if we re-execute again and again the rendom values will remain same:

In [35]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [40]:
np.random.seed(101)
ranarr=np.random.randint(0,101,10)

In [41]:
ranarr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

# To get the maximum value in ranarr:

In [42]:
ranarr.max()

95

# To get the minimum value in ranarr:

In [43]:
ranarr.min()

9

# To get the index number of the maximum value:

In [44]:
ranarr.argmax()

0

# To get the index number of the minimum value:

In [45]:
ranarr.argmin()

7

# To get data type:

In [47]:
ranarr.dtype

dtype('int32')

In [48]:
arr=np.arange(0,25)

In [49]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

# To get the shape of arr:

In [50]:
arr.shape

(25,)

# To reshape the arr:

In [51]:
arr=arr.reshape(5,5)

In [52]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [53]:
arr.shape

(5, 5)