# Importing the necessary library: 

In [1]:
import numpy as np

# Creating an array :

In [2]:
arr=np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# To get the value according to the index value:

In [4]:
arr[8]

8

# To get the values from 0 index till index number 5:

In [5]:
arr[:5]

array([0, 1, 2, 3, 4])

# To get the values from the index number 5 till end:

In [6]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

# In list we can make broadcasting to the values:

In [7]:
arr[:5]=100

# Let's check the arr values:

In [8]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [9]:
arr=np.arange(0,11)

# Let's create slice_of_arr which is part of arr:

In [16]:
slice_of_arr=arr[0:5]

In [17]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [18]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Let's convert the slice_of_arr values to 99:

In [20]:
slice_of_arr[:]=99

In [21]:
slice_of_arr

array([99, 99, 99, 99, 99])

# Let's check the values of arr:

In [22]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

# If we want to avoid the broadcasting:

In [23]:
arr_copy=arr.copy()

# Now let's change the arr_copy values:

In [25]:
arr_copy[:]=100

# Let's view the values of arr_copy:

In [26]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

# Now let's check the arr values:

In [27]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

# Now let's create 2D array

In [28]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [29]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

# To check arr_2d's shape:

In [30]:
arr_2d.shape

(3, 3)

# If we want to check the the first row:

In [32]:
arr_2d[0]

array([ 5, 10, 15])

# If we want to check the 3rd row:

In [33]:
arr_2d[2]

array([35, 40, 45])

# If we want to get a single value such as 25:

In [34]:
arr_2d[1][1]

25

# Or we can write the address in a single list

In [35]:
arr_2d[1,1]

25

In [36]:
arr_2d[0,2]

15

# To call a group of values:

In [37]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [38]:
arr=np.arange(1,11)

In [39]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# To check the values of arr in a boolian way:

In [40]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [41]:
bool_arr=arr>4

In [42]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

# To get the values to true boolians only

In [43]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [44]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [45]:
arr=np.arange(0,10)

In [46]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# To add 5 to all arr values:

In [47]:
arr+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# To sub from all arr values 2:

In [48]:
arr-2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

# To add 2 arrays:

In [49]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

# To devide 2 arrays(will get warning due to the deviding by 0):

In [50]:
arr/arr

<ipython-input-50-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

# To devide all arr values on with 1(will get warning becauseof the 0 value in arr):

In [51]:
1/arr

<ipython-input-51-016353831300>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

# If we want to get the square root of all arr values:

In [52]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

# To get the sin of each arr values:

In [53]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

# To get the total of arr values:

In [54]:
arr.sum()

45

# To get the average or mean of arr values:

In [55]:
arr.mean()

4.5

# To get the maximum value of arr:

In [56]:
arr.max()

9

# To get the minimum value of arr:

In [57]:
arr.min()

0

# To get the varience of arr values:

In [58]:
arr.var()

8.25

# To get the standard deviation of arr:

In [59]:
arr.std()

2.8722813232690143

# To create aray and reshape it at the same step:

In [60]:
arr2d=np.arange(0,25).reshape(5,5)

In [61]:
arr2d.shape

(5, 5)

In [62]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# To get the sum of the all arr2d values:

In [63]:
arr2d.sum()

300

# To get the sum of each column:

In [64]:
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

# To get the sum of each row:

In [65]:
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])